backend:
  name: git-gateway
  branch: master

media_folder: "src/assets/images/min" # Folder where user uploaded files should go
public_folder: "/assets/images/min" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Blogs"
    name: "blogs"
    folder: "src/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Product's image gallery"
    name: "gallery"
    files:
      - label: "Accordion Shutters"
        name: "image-accordion-gallery"
        file: "src/_data/products/accordion.json"
        fields:
          - label: "Image"
            name: "image"
            widget: "list"
            fields:
              - {label: "src", name: "src", widget: "image"}
              - {label: "alt", name: "alt", widget: "string"}
      - label: "Impact Windows"
        name: "image-windows-gallery"
        file: "src/_data/products/impact.json"
        fields:
          - label: "Image"
            name: "image"
            widget: "list"
            fields:
              - {label: "src", name: "src", widget: "image"}
              - {label: "alt", name: "alt", widget: "string"}
      - label: "Metal Roofing"
        name: "image-roofing-gallery"
        file: "src/_data/products/roofing.json"
        fields:
          - label: "Image"
            name: "image"
            widget: "list"
            fields:
              - {label: "src", name: "src", widget: "image"}
              - {label: "alt", name: "alt", widget: "string"}
      - label: "Aluminum Pergolas"
        name: "image-pergolas-gallery"
        file: "src/_data/products/pergola.json"
        fields:
          - label: "Image"
            name: "image"
            widget: "list"
            fields:
              - {label: "src", name: "src", widget: "image"}
              - {label: "alt", name: "alt", widget: "string"}
      - label: "Fencing and Decking"
        name: "image-fencing-gallery"
        file: "src/_data/products/fencing.json"
        fields:
          - label: "Image"
            name: "image"
            widget: "list"
            fields:
              - {label: "src", name: "src", widget: "image"}
              - {label: "alt", name: "alt", widget: "string"}
      - label: "Seamless Gutters"
        name: "image-gutters-gallery"
        file: "src/_data/products/gutters.json"
        fields:
          - label: "Image"
            name: "image"
            widget: "list"
            fields:
              - {label: "src", name: "src", widget: "image"}
              - {label: "alt", name: "alt", widget: "string"}